services:
  mysql:
    image: mysql:8.0
    container_name: kata_product_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: products
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - kata-network
    command: [ '--default-authentication-plugin=mysql_native_password' ]
    restart: unless-stopped
    stop_grace_period: 30s

  symfony:
    build:
      context: ./data/docker/back
    container_name: kata_symfony_app
    working_dir: /var/www/html
    expose:
      - 9000
    volumes:
      - ./back:/var/www/html
    depends_on:
      - mysql
    networks:
      - kata-network
    environment:
      APP_ENV: dev
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:alpine
    container_name: kata_symfony_web
    ports:
      - "8989:80"
    volumes:
      - ./back:/var/www/html
      - ./data/docker/nginx/drupal-default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - symfony
    networks:
      - kata-network


volumes:
  mysql_data:

networks:
  kata-network:
    driver: bridge